### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by recalcitrantsupplant** [surroundaustralia/clean_ttl_hook#1]
Include that it:
- removes unused prefixes
- reorders prefixes alphabetically

include simple before after example

include example .pre-commit-config.yaml file:
```
repos:
-   repo: https://github.com/surroundaustralia/clean_ttl_hook
    rev: 6624063f616e69f2394d37d9d6694e4eb2ba9d53
    hooks:
      - id: clean_ttl
```
Link to pre commit website for further details on how to install / set up pre commit
